package com.habitsfirst.androidclone.data.local.migrations

import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.habitsfirst.androidclone.data.local.AppDatabase
import org.junit.Rule
import org.junit.Test

/**
 * The idiomatic, Room-blessed way to test [Migrations.kt][com.habitsfirst.androidclone.data.local.migrations]:
 * [MigrationTestHelper] creates a real on-disk database from a historical
 * `app/schemas/.../<version>.json`, runs the real [androidx.room.migration.Migration]
 * objects against it via Room itself, and validates the result against the target
 * version's schema JSON (identity hash, every table's columns/indices/foreign keys).
 *
 * **This class has not been run in CI or locally as part of this change.**
 * [MigrationTestHelper] resolves its target via
 * `androidx.test.platform.app.InstrumentationRegistry`, so -- like every other test under
 * `app/src/androidTest` -- it only executes as an *instrumented* test
 * (`./gradlew connectedAndroidTest`) against a real device or emulator, and the sandbox
 * this migration work was done in has neither. It has been checked for compile
 * correctness (`./gradlew compileDebugAndroidTestKotlin`) but not executed; run
 * `connectedAndroidTest` on a device/emulator before relying on it. The genuinely-executed
 * verification for this change is `MigrationsSqlTest` under `app/src/test`, which runs the
 * same `MIGRATION_x_y_SQL` statements against a real (JVM-native) SQLite engine -- see its
 * KDoc for what it does and doesn't prove.
 *
 * `1.json`, `7.json`, and `8.json` under
 * `app/schemas/com.habitsfirst.androidclone.data.local.AppDatabase/` (the non-final
 * versions this class needs) are hand-authored from the historical entity definitions at
 * those versions, not generated by a build at that commit -- `9.json` is the only one
 * this repository has ever actually built (see `Migrations.kt`'s KDoc for why versions
 * 2/3 don't have their own schema files: no real device was ever at exactly v2 or v3, so
 * no test here starts from one).
 */
class MigrationsInstrumentedTest {

    @get:Rule
    val helper: MigrationTestHelper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory(),
    )

    @Test
    fun migrate1To9_fullChain_matchesCurrentSchema() {
        helper.createDatabase(TEST_DB, 1).close()

        helper.runMigrationsAndValidate(TEST_DB, 9, true, *ALL_MIGRATIONS)
    }

    /**
     * The trickiest step in the chain, isolated: seeds v8 rows exercising every branch of
     * [MIGRATION_8_9]'s habit-type remap (EXERCISE_MINUTES/MEDITATION_MINUTES ->
     * TIMED_MINUTES; CUSTOM with/without requiresPhotoVerification -> PHOTO/TALLY), then
     * migrates to v9 and asserts both the remap and that `requiresPhotoVerification` is
     * really gone.
     */
    @Test
    fun migrate8To9_remapsHabitTypesAndDropsRequiresPhotoVerification() {
        val db = helper.createDatabase(TEST_DB, 8)
        db.execSQL(
            "INSERT INTO habits (name, type, targetValue, targetPackageName, targetAppLabel, sortOrder, createdAtEpochMillis, isArchived, requiresPhotoVerification, kind, scheduledDaysMask) " +
                "VALUES ('Run', 'EXERCISE_MINUTES', 20, NULL, NULL, 0, 0, 0, 0, 'GATING', 0)",
        )
        db.execSQL(
            "INSERT INTO habits (name, type, targetValue, targetPackageName, targetAppLabel, sortOrder, createdAtEpochMillis, isArchived, requiresPhotoVerification, kind, scheduledDaysMask) " +
                "VALUES ('Proof of workout', 'CUSTOM', 0, NULL, NULL, 1, 0, 0, 1, 'GATING', 0)",
        )
        db.execSQL(
            "INSERT INTO habits (name, type, targetValue, targetPackageName, targetAppLabel, sortOrder, createdAtEpochMillis, isArchived, requiresPhotoVerification, kind, scheduledDaysMask) " +
                "VALUES ('Make bed', 'CUSTOM', 0, NULL, NULL, 2, 0, 0, 0, 'GATING', 0)",
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(TEST_DB, 9, true, MIGRATION_8_9)

        migrated.query("SELECT type FROM habits ORDER BY sortOrder").use { cursor ->
            val types = generateSequence { if (cursor.moveToNext()) cursor.getString(0) else null }.toList()
            check(types == listOf("TIMED_MINUTES", "PHOTO", "TALLY")) {
                "Expected [TIMED_MINUTES, PHOTO, TALLY] but got $types"
            }
        }
    }

    /**
     * `HabitType.IMAGE_VERIFICATION` was a real, distinct type through v7 -- [MIGRATION_7_8]
     * must rewrite it to `type = 'CUSTOM', requiresPhotoVerification = 1` rather than
     * leaving the now-nonexistent enum name in place (which would throw on
     * `HabitType.valueOf(type)` at the very next app launch).
     */
    @Test
    fun migrate7To8_remapsImageVerificationToCustomWithToggleSet() {
        val db = helper.createDatabase(TEST_DB, 7)
        db.execSQL(
            "INSERT INTO habits (name, type, targetValue, targetPackageName, targetAppLabel, sortOrder, createdAtEpochMillis, isArchived, kind, scheduledDaysMask) " +
                "VALUES ('Proof of workout', 'IMAGE_VERIFICATION', 0, NULL, NULL, 0, 0, 0, 'GATING', 0)",
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(TEST_DB, 8, true, MIGRATION_7_8)

        migrated.query("SELECT type, requiresPhotoVerification FROM habits").use { cursor ->
            check(cursor.moveToFirst()) { "Expected the seeded habit row to still be present" }
            check(cursor.getString(0) == "CUSTOM") { "Expected type='CUSTOM' but got '${cursor.getString(0)}'" }
            check(cursor.getInt(1) == 1) { "Expected requiresPhotoVerification=1 but got ${cursor.getInt(1)}" }
        }
    }

    private companion object {
        const val TEST_DB = "migration-test"
    }
}
